(* Generated by rocq-of-rust *)
Require Import RocqOfRust.RocqOfRust.

(* StructRecord
  {
    name := "Droppable";
    const_params := [];
    ty_params := [];
    fields := [ ("name", Ty.apply (Ty.path "&") [] [ Ty.path "str" ]) ];
  } *)

Module Impl_core_ops_drop_Drop_for_drop_Droppable.
  Definition Self : Ty.t := Ty.path "drop::Droppable".
  
  (*
      fn drop(&mut self) {
          println!("> Dropping {}", self.name);
      }
  *)
  Definition drop (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
    match ε, τ, α with
    | [], [], [ self ] =>
      ltac:(M.monadic
        (let self :=
          M.alloc (| Ty.apply (Ty.path "&mut") [] [ Ty.path "drop::Droppable" ], self |) in
        M.read (|
          let~ _ : Ty.tuple [] :=
            M.read (|
              let~ _ : Ty.tuple [] :=
                M.call_closure (|
                  Ty.tuple [],
                  M.get_function (| "std::io::stdio::_print", [], [] |),
                  [
                    M.read (|
                      let~ args :
                          Ty.tuple
                            [
                              Ty.apply
                                (Ty.path "&")
                                []
                                [ Ty.apply (Ty.path "&") [] [ Ty.path "str" ] ]
                            ] :=
                        Value.Tuple
                          [
                            M.borrow (|
                              Pointer.Kind.Ref,
                              M.SubPointer.get_struct_record_field (|
                                M.deref (| M.read (| self |) |),
                                "drop::Droppable",
                                "name"
                              |)
                            |)
                          ] in
                      let~ args :
                          Ty.apply
                            (Ty.path "array")
                            [ Value.Integer IntegerKind.Usize 1 ]
                            [ Ty.path "core::fmt::rt::Argument" ] :=
                        Value.Array
                          [
                            M.call_closure (|
                              Ty.path "core::fmt::rt::Argument",
                              M.get_associated_function (|
                                Ty.path "core::fmt::rt::Argument",
                                "new_display",
                                [],
                                [ Ty.apply (Ty.path "&") [] [ Ty.path "str" ] ]
                              |),
                              [
                                M.borrow (|
                                  Pointer.Kind.Ref,
                                  M.deref (|
                                    M.read (| M.SubPointer.get_tuple_field (| args, 0 |) |)
                                  |)
                                |)
                              ]
                            |)
                          ] in
                      M.alloc (|
                        Ty.path "core::fmt::Arguments",
                        M.call_closure (|
                          Ty.path "core::fmt::Arguments",
                          M.get_associated_function (|
                            Ty.path "core::fmt::Arguments",
                            "new",
                            [ Value.Integer IntegerKind.Usize 16; Value.Integer IntegerKind.Usize 1
                            ],
                            []
                          |),
                          [
                            M.borrow (|
                              Pointer.Kind.Ref,
                              M.deref (|
                                M.mk_byte_str_ref
                                  16
                                  [
                                    11;
                                    62;
                                    32;
                                    68;
                                    114;
                                    111;
                                    112;
                                    112;
                                    105;
                                    110;
                                    103;
                                    32;
                                    192;
                                    1;
                                    10;
                                    0
                                  ]
                              |)
                            |);
                            M.borrow (|
                              Pointer.Kind.Ref,
                              M.deref (| M.borrow (| Pointer.Kind.Ref, args |) |)
                            |)
                          ]
                        |)
                      |)
                    |)
                  ]
                |) in
              M.alloc (| Ty.tuple [], Value.Tuple [] |)
            |) in
          M.alloc (| Ty.tuple [], Value.Tuple [] |)
        |)))
    | _, _, _ => M.impossible "wrong number of arguments"
    end.
  
  Axiom Implements :
    M.IsTraitInstance
      "core::ops::drop::Drop"
      (* Trait polymorphic consts *) []
      (* Trait polymorphic types *) []
      Self
      (* Instance *) [ ("drop", InstanceField.Method drop) ].
End Impl_core_ops_drop_Drop_for_drop_Droppable.

(*
fn main() {
    let _a = Droppable { name: "a" };

    // block A
    {
        let _b = Droppable { name: "b" };

        // block B
        {
            let _c = Droppable { name: "c" };
            let _d = Droppable { name: "d" };

            println!("Exiting block B");
        }
        println!("Just exited block B");

        println!("Exiting block A");
    }
    println!("Just exited block A");

    // Variable can be manually dropped using the `drop` function
    drop(_a);
    // TODO ^ Try commenting this line

    println!("end of the main function");

    // `_a` *won't* be `drop`ed again here, because it already has been
    // (manually) `drop`ed
}
*)
Definition main (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
  match ε, τ, α with
  | [], [], [] =>
    ltac:(M.monadic
      (M.read (|
        let~ _a : Ty.path "drop::Droppable" :=
          Value.mkStructRecord "drop::Droppable" [] [] [ ("name", mk_str (| "a" |)) ] in
        let~ _ : Ty.tuple [] :=
          M.read (|
            let~ _b : Ty.path "drop::Droppable" :=
              Value.mkStructRecord "drop::Droppable" [] [] [ ("name", mk_str (| "b" |)) ] in
            let~ _ : Ty.tuple [] :=
              M.read (|
                let~ _c : Ty.path "drop::Droppable" :=
                  Value.mkStructRecord "drop::Droppable" [] [] [ ("name", mk_str (| "c" |)) ] in
                let~ _d : Ty.path "drop::Droppable" :=
                  Value.mkStructRecord "drop::Droppable" [] [] [ ("name", mk_str (| "d" |)) ] in
                let~ _ : Ty.tuple [] :=
                  M.read (|
                    let~ _ : Ty.tuple [] :=
                      M.call_closure (|
                        Ty.tuple [],
                        M.get_function (| "std::io::stdio::_print", [], [] |),
                        [
                          M.call_closure (|
                            Ty.path "core::fmt::Arguments",
                            M.get_associated_function (|
                              Ty.path "core::fmt::Arguments",
                              "from_str",
                              [],
                              []
                            |),
                            [ mk_str (| "Exiting block B
" |) ]
                          |)
                        ]
                      |) in
                    M.alloc (| Ty.tuple [], Value.Tuple [] |)
                  |) in
                M.alloc (| Ty.tuple [], Value.Tuple [] |)
              |) in
            let~ _ : Ty.tuple [] :=
              M.read (|
                let~ _ : Ty.tuple [] :=
                  M.call_closure (|
                    Ty.tuple [],
                    M.get_function (| "std::io::stdio::_print", [], [] |),
                    [
                      M.call_closure (|
                        Ty.path "core::fmt::Arguments",
                        M.get_associated_function (|
                          Ty.path "core::fmt::Arguments",
                          "from_str",
                          [],
                          []
                        |),
                        [ mk_str (| "Just exited block B
" |) ]
                      |)
                    ]
                  |) in
                M.alloc (| Ty.tuple [], Value.Tuple [] |)
              |) in
            let~ _ : Ty.tuple [] :=
              M.read (|
                let~ _ : Ty.tuple [] :=
                  M.call_closure (|
                    Ty.tuple [],
                    M.get_function (| "std::io::stdio::_print", [], [] |),
                    [
                      M.call_closure (|
                        Ty.path "core::fmt::Arguments",
                        M.get_associated_function (|
                          Ty.path "core::fmt::Arguments",
                          "from_str",
                          [],
                          []
                        |),
                        [ mk_str (| "Exiting block A
" |) ]
                      |)
                    ]
                  |) in
                M.alloc (| Ty.tuple [], Value.Tuple [] |)
              |) in
            M.alloc (| Ty.tuple [], Value.Tuple [] |)
          |) in
        let~ _ : Ty.tuple [] :=
          M.read (|
            let~ _ : Ty.tuple [] :=
              M.call_closure (|
                Ty.tuple [],
                M.get_function (| "std::io::stdio::_print", [], [] |),
                [
                  M.call_closure (|
                    Ty.path "core::fmt::Arguments",
                    M.get_associated_function (|
                      Ty.path "core::fmt::Arguments",
                      "from_str",
                      [],
                      []
                    |),
                    [ mk_str (| "Just exited block A
" |) ]
                  |)
                ]
              |) in
            M.alloc (| Ty.tuple [], Value.Tuple [] |)
          |) in
        let~ _ : Ty.tuple [] :=
          M.call_closure (|
            Ty.tuple [],
            M.get_function (| "core::mem::drop", [], [ Ty.path "drop::Droppable" ] |),
            [ M.read (| _a |) ]
          |) in
        let~ _ : Ty.tuple [] :=
          M.read (|
            let~ _ : Ty.tuple [] :=
              M.call_closure (|
                Ty.tuple [],
                M.get_function (| "std::io::stdio::_print", [], [] |),
                [
                  M.call_closure (|
                    Ty.path "core::fmt::Arguments",
                    M.get_associated_function (|
                      Ty.path "core::fmt::Arguments",
                      "from_str",
                      [],
                      []
                    |),
                    [ mk_str (| "end of the main function
" |) ]
                  |)
                ]
              |) in
            M.alloc (| Ty.tuple [], Value.Tuple [] |)
          |) in
        M.alloc (| Ty.tuple [], Value.Tuple [] |)
      |)))
  | _, _, _ => M.impossible "wrong number of arguments"
  end.

Global Instance Instance_IsFunction_main : M.IsFunction.C "drop::main" main.
Proof.
Admitted.
Global Typeclasses Opaque main.

Definition function_table : list (string * PolymorphicFunction.t) := [ ("drop::main", main) ].

Definition trait_method_table : list (string * list Ty.t * Ty.t * string * PolymorphicFunction.t) :=
  [
    ("core::ops::drop::Drop",
      [],
      Ty.path "drop::Droppable",
      "drop",
      Impl_core_ops_drop_Drop_for_drop_Droppable.drop)
  ].
