(* Generated by coq-of-rust *)
Require Import CoqOfRust.CoqOfRust.

Parameter foo : (list Value.t) -> (list Ty.t) -> (list Value.t) -> M.

Global Instance Instance_IsFunction_foo : M.IsFunction.Trait "concurrent_tests::foo" foo.
Admitted.

Module tests.
  Parameter test_file : (list Value.t) -> (list Ty.t) -> (list Value.t) -> M.
  
  Global Instance Instance_IsFunction_test_file :
    M.IsFunction.Trait "concurrent_tests::tests::test_file'1" test_file.
  Admitted.
  
  Parameter test_file_also : (list Value.t) -> (list Ty.t) -> (list Value.t) -> M.
  
  Global Instance Instance_IsFunction_test_file_also :
    M.IsFunction.Trait "concurrent_tests::tests::test_file_also'1" test_file_also.
  Admitted.
End tests.
