[package]
name = "template"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
scale = { path = "lib/scale" }
derive_more = { version = "0.99", default-features = false, features = ["from", "display"] }