(* Generated by coq-of-rust *)
Require Import CoqOfRust.CoqOfRust.

(* #[allow(dead_code)] - function was ignored by the compiler *)
Parameter main : forall `{State.Trait}, M unit.

Parameter apply :
    forall
      `{State.Trait}
      {F : Set}
      {ℋ_0 : core.ops.function.FnOnce.Trait F (Args := unit)},
    F -> M unit.
