(* Generated by coq-of-rust *)
Require Import CoqOfRust.CoqOfRust.





Module  Animal.
Section Animal.
  Class Trait (Self : Set) : Type := {
    noise :
      Ty.function
        [Ty.apply (Ty.path "ref") [Self]]
        (Ty.apply (Ty.path "ref") [Ty.path "str"]);
  }.
  
End Animal.
End Animal.

Module  Impl_returning_traits_with_dyn_Animal_for_returning_traits_with_dyn_Sheep.
Section Impl_returning_traits_with_dyn_Animal_for_returning_traits_with_dyn_Sheep.
  Definition Self : Ty.t :=
    Ty.apply (Ty.path "returning_traits_with_dyn::Sheep") [].
  
  Parameter noise :
      (Ty.apply
          (Ty.path "ref")
          [Ty.apply (Ty.path "returning_traits_with_dyn::Sheep") []])
        ->
        Ty.apply (Ty.path "ref") [Ty.path "str"].
  
  Definition AssociatedFunction_noise : Instance.t := {
    Notations.double_colon := noise;
  }.
  
  Definition ℐ : Instance.t := [("noise", noise)].
End Impl_returning_traits_with_dyn_Animal_for_returning_traits_with_dyn_Sheep.
End Impl_returning_traits_with_dyn_Animal_for_returning_traits_with_dyn_Sheep.

Module  Impl_returning_traits_with_dyn_Animal_for_returning_traits_with_dyn_Cow.
Section Impl_returning_traits_with_dyn_Animal_for_returning_traits_with_dyn_Cow.
  Definition Self : Ty.t :=
    Ty.apply (Ty.path "returning_traits_with_dyn::Cow") [].
  
  Parameter noise :
      (Ty.apply
          (Ty.path "ref")
          [Ty.apply (Ty.path "returning_traits_with_dyn::Cow") []])
        ->
        Ty.apply (Ty.path "ref") [Ty.path "str"].
  
  Definition AssociatedFunction_noise : Instance.t := {
    Notations.double_colon := noise;
  }.
  
  Definition ℐ : Instance.t := [("noise", noise)].
End Impl_returning_traits_with_dyn_Animal_for_returning_traits_with_dyn_Cow.
End Impl_returning_traits_with_dyn_Animal_for_returning_traits_with_dyn_Cow.

Parameter random_animal :
    (Ty.path "f64") ->
      Ty.apply
        (Ty.path "alloc::boxed::Box")
        [dyn [returning_traits_with_dyn.Animal.Trait];
          Ty.apply (Ty.path "alloc::alloc::Global") []].

(* #[allow(dead_code)] - function was ignored by the compiler *)
Parameter main : Ty.path "unit".
