(* Generated by coq-of-rust *)
Require Import CoqOfRust.CoqOfRust.

(*
fn main() {
    'outer: loop {
        println!("Entered the outer loop");

        'inner: loop {
            println!("Entered the inner loop");

            // This would break only the inner loop
            //break;

            // This breaks the outer loop
            break 'outer;
        }

        println!("This point will never be reached");
    }

    println!("Exited the outer loop");
}
*)
Definition main (τ : list Ty.t) (α : list Value.t) : M :=
  match τ, α with
  | [], [] =>
    ltac:(M.monadic
      (M.read (|
          let _ :=
            M.loop (|
                ltac:(M.monadic
                  (let _ :=
                    let _ :=
                      M.alloc (|
                          M.call_closure (|
                              M.get_function (| "std::io::stdio::_print", [] |),
                              [
                                M.call_closure (|
                                    M.get_associated_function (|
                                        Ty.path "core::fmt::Arguments",
                                        "new_const",
                                        []
                                      |),
                                    [
                                      (* Unsize *)
                                        M.pointer_coercion
                                          (M.alloc (|
                                              Value.Array
                                                [ M.read (| mk_str "Entered the outer loop
" |) ]
                                            |))
                                    ]
                                  |)
                              ]
                            |)
                        |) in
                    M.alloc (| Value.Tuple [] |) in
                  let _ :=
                    M.alloc (|
                        M.never_to_any (|
                            M.read (|
                                M.loop (|
                                    ltac:(M.monadic
                                      (let _ :=
                                        let _ :=
                                          M.alloc (|
                                              M.call_closure (|
                                                  M.get_function (| "std::io::stdio::_print", [] |),
                                                  [
                                                    M.call_closure (|
                                                        M.get_associated_function (|
                                                            Ty.path "core::fmt::Arguments",
                                                            "new_const",
                                                            []
                                                          |),
                                                        [
                                                          (* Unsize *)
                                                            M.pointer_coercion
                                                              (M.alloc (|
                                                                  Value.Array
                                                                    [
                                                                      M.read (|
                                                                          mk_str
                                                                            "Entered the inner loop
"
                                                                        |)
                                                                    ]
                                                                |))
                                                        ]
                                                      |)
                                                  ]
                                                |)
                                            |) in
                                        M.alloc (| Value.Tuple [] |) in
                                      M.break (||)))
                                  |)
                              |)
                          |)
                      |) in
                  let _ :=
                    let _ :=
                      M.alloc (|
                          M.call_closure (|
                              M.get_function (| "std::io::stdio::_print", [] |),
                              [
                                M.call_closure (|
                                    M.get_associated_function (|
                                        Ty.path "core::fmt::Arguments",
                                        "new_const",
                                        []
                                      |),
                                    [
                                      (* Unsize *)
                                        M.pointer_coercion
                                          (M.alloc (|
                                              Value.Array
                                                [
                                                  M.read (|
                                                      mk_str "This point will never be reached
"
                                                    |)
                                                ]
                                            |))
                                    ]
                                  |)
                              ]
                            |)
                        |) in
                    M.alloc (| Value.Tuple [] |) in
                  M.alloc (| Value.Tuple [] |)))
              |) in
          let _ :=
            let _ :=
              M.alloc (|
                  M.call_closure (|
                      M.get_function (| "std::io::stdio::_print", [] |),
                      [
                        M.call_closure (|
                            M.get_associated_function (|
                                Ty.path "core::fmt::Arguments",
                                "new_const",
                                []
                              |),
                            [
                              (* Unsize *)
                                M.pointer_coercion
                                  (M.alloc (|
                                      Value.Array [ M.read (| mk_str "Exited the outer loop
" |) ]
                                    |))
                            ]
                          |)
                      ]
                    |)
                |) in
            M.alloc (| Value.Tuple [] |) in
          M.alloc (| Value.Tuple [] |)
        |)))
  | _, _ => M.impossible
  end.
