(* Generated by coq-of-rust *)
Require Import CoqOfRust.CoqOfRust.

Import Root.std.prelude.rust_2015.

Definition main (_ : unit) : unit := Stmt_item.

Module Foo.
  Record t : Set := {
    x : u32 * u32;
    y : u32;
  }.
End Foo.
Definition Foo : Set := Foo.t.
