(* Generated by coq-of-rust *)
Require Import CoqOfRust.CoqOfRust.

Parameter main : (list Value.t) -> (list Ty.t) -> (list Value.t) -> M.

Global Instance Instance_IsFunction_main :
  M.IsFunction.C "diverging_functions_example_sum_odd_numbers::main" main.
Admitted.

Module main.
  Parameter sum_odd_numbers : (list Value.t) -> (list Ty.t) -> (list Value.t) -> M.
  
  Global Instance Instance_IsFunction_sum_odd_numbers :
    M.IsFunction.C
      "diverging_functions_example_sum_odd_numbers::main::sum_odd_numbers"
      sum_odd_numbers.
  Admitted.
End main.
