(* Generated by coq-of-rust *)
Require Import CoqOfRust.CoqOfRust.

(* #[allow(dead_code)] - function was ignored by the compiler *)
Definition main : M (M.Val unit) :=
  M.function_body
    (let* child : ltac:(refine (M.Val std.process.Child.t)) :=
      let* α0 : ltac:(refine (M.Val std.process.Command.t)) :=
        std.process.Command.t::["new"] (mk_str "sleep") in
      let* α1 : ltac:(refine (M.Val (mut_ref std.process.Command.t))) :=
        borrow_mut α0 in
      let* α2 : ltac:(refine (M.Val (mut_ref std.process.Command.t))) :=
        std.process.Command.t::["arg"] α1 (mk_str "5") in
      let* α3 : ltac:(refine (M.Val std.process.Command.t)) := deref α2 in
      let* α4 : ltac:(refine (M.Val (mut_ref std.process.Command.t))) :=
        borrow_mut α3 in
      let* α5 :
          ltac:(refine
            (M.Val
              (core.result.Result.t
                std.process.Child.t
                std.io.error.Error.t))) :=
        std.process.Command.t::["spawn"] α4 in
      (core.result.Result.t
            std.process.Child.t
            std.io.error.Error.t)::["unwrap"]
        α5 in
    let* _result : ltac:(refine (M.Val std.process.ExitStatus.t)) :=
      let* α0 : ltac:(refine (M.Val (mut_ref std.process.Child.t))) :=
        borrow_mut child in
      let* α1 :
          ltac:(refine
            (M.Val
              (core.result.Result.t
                std.process.ExitStatus.t
                std.io.error.Error.t))) :=
        std.process.Child.t::["wait"] α0 in
      (core.result.Result.t
            std.process.ExitStatus.t
            std.io.error.Error.t)::["unwrap"]
        α1 in
    let* _ : ltac:(refine (M.Val unit)) :=
      let* _ : ltac:(refine (M.Val unit)) :=
        let* α0 : ltac:(refine (M.Val (array (ref str)))) :=
          M.alloc [ mk_str "reached end of main
" ] in
        let* α1 : ltac:(refine (M.Val (ref (array (ref str))))) := borrow α0 in
        let* α2 : ltac:(refine (M.Val (ref (slice (ref str))))) :=
          pointer_coercion "Unsize" α1 in
        let* α3 : ltac:(refine (M.Val core.fmt.Arguments.t)) :=
          core.fmt.Arguments.t::["new_const"] α2 in
        std.io.stdio._print α3 in
      M.alloc tt in
    M.alloc tt).
