(* Generated by rocq-of-rust *)
Require Import RocqOfRust.RocqOfRust.

(*
fn compare_prints<T: Debug + Display>(t: &T) {
    println!("Debug: `{:?}`", t);
    println!("Display: `{}`", t);
}
*)
Definition compare_prints (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
  match ε, τ, α with
  | [], [ T ], [ t ] =>
    ltac:(M.monadic
      (let t := M.alloc (| Ty.apply (Ty.path "&") [] [ T ], t |) in
      M.read (|
        let~ _ : Ty.tuple [] :=
          M.read (|
            let~ _ : Ty.tuple [] :=
              M.call_closure (|
                Ty.tuple [],
                M.get_function (| "std::io::stdio::_print", [], [] |),
                [
                  M.read (|
                    let~ args :
                        Ty.tuple
                          [ Ty.apply (Ty.path "&") [] [ Ty.apply (Ty.path "&") [] [ T ] ] ] :=
                      Value.Tuple [ M.borrow (| Pointer.Kind.Ref, t |) ] in
                    let~ args :
                        Ty.apply
                          (Ty.path "array")
                          [ Value.Integer IntegerKind.Usize 1 ]
                          [ Ty.path "core::fmt::rt::Argument" ] :=
                      Value.Array
                        [
                          M.call_closure (|
                            Ty.path "core::fmt::rt::Argument",
                            M.get_associated_function (|
                              Ty.path "core::fmt::rt::Argument",
                              "new_debug",
                              [],
                              [ Ty.apply (Ty.path "&") [] [ T ] ]
                            |),
                            [
                              M.borrow (|
                                Pointer.Kind.Ref,
                                M.deref (|
                                  M.read (| M.SubPointer.get_tuple_field (| args, 0 |) |)
                                |)
                              |)
                            ]
                          |)
                        ] in
                    M.alloc (|
                      Ty.path "core::fmt::Arguments",
                      M.call_closure (|
                        Ty.path "core::fmt::Arguments",
                        M.get_associated_function (|
                          Ty.path "core::fmt::Arguments",
                          "new",
                          [ Value.Integer IntegerKind.Usize 14; Value.Integer IntegerKind.Usize 1 ],
                          []
                        |),
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (|
                              M.mk_byte_str_ref
                                14
                                [ 8; 68; 101; 98; 117; 103; 58; 32; 96; 192; 2; 96; 10; 0 ]
                            |)
                          |);
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.borrow (| Pointer.Kind.Ref, args |) |)
                          |)
                        ]
                      |)
                    |)
                  |)
                ]
              |) in
            M.alloc (| Ty.tuple [], Value.Tuple [] |)
          |) in
        let~ _ : Ty.tuple [] :=
          M.read (|
            let~ _ : Ty.tuple [] :=
              M.call_closure (|
                Ty.tuple [],
                M.get_function (| "std::io::stdio::_print", [], [] |),
                [
                  M.read (|
                    let~ args :
                        Ty.tuple
                          [ Ty.apply (Ty.path "&") [] [ Ty.apply (Ty.path "&") [] [ T ] ] ] :=
                      Value.Tuple [ M.borrow (| Pointer.Kind.Ref, t |) ] in
                    let~ args :
                        Ty.apply
                          (Ty.path "array")
                          [ Value.Integer IntegerKind.Usize 1 ]
                          [ Ty.path "core::fmt::rt::Argument" ] :=
                      Value.Array
                        [
                          M.call_closure (|
                            Ty.path "core::fmt::rt::Argument",
                            M.get_associated_function (|
                              Ty.path "core::fmt::rt::Argument",
                              "new_display",
                              [],
                              [ Ty.apply (Ty.path "&") [] [ T ] ]
                            |),
                            [
                              M.borrow (|
                                Pointer.Kind.Ref,
                                M.deref (|
                                  M.read (| M.SubPointer.get_tuple_field (| args, 0 |) |)
                                |)
                              |)
                            ]
                          |)
                        ] in
                    M.alloc (|
                      Ty.path "core::fmt::Arguments",
                      M.call_closure (|
                        Ty.path "core::fmt::Arguments",
                        M.get_associated_function (|
                          Ty.path "core::fmt::Arguments",
                          "new",
                          [ Value.Integer IntegerKind.Usize 16; Value.Integer IntegerKind.Usize 1 ],
                          []
                        |),
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (|
                              M.mk_byte_str_ref
                                16
                                [ 10; 68; 105; 115; 112; 108; 97; 121; 58; 32; 96; 192; 2; 96; 10; 0
                                ]
                            |)
                          |);
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.borrow (| Pointer.Kind.Ref, args |) |)
                          |)
                        ]
                      |)
                    |)
                  |)
                ]
              |) in
            M.alloc (| Ty.tuple [], Value.Tuple [] |)
          |) in
        M.alloc (| Ty.tuple [], Value.Tuple [] |)
      |)))
  | _, _, _ => M.impossible "wrong number of arguments"
  end.

Global Instance Instance_IsFunction_compare_prints :
  M.IsFunction.C "generics_multiple_bounds::compare_prints" compare_prints.
Proof.
Admitted.
Global Typeclasses Opaque compare_prints.

(*
fn compare_types<T: Debug, U: Debug>(t: &T, u: &U) {
    println!("t: `{:?}`", t);
    println!("u: `{:?}`", u);
}
*)
Definition compare_types (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
  match ε, τ, α with
  | [], [ T; U ], [ t; u ] =>
    ltac:(M.monadic
      (let t := M.alloc (| Ty.apply (Ty.path "&") [] [ T ], t |) in
      let u := M.alloc (| Ty.apply (Ty.path "&") [] [ U ], u |) in
      M.read (|
        let~ _ : Ty.tuple [] :=
          M.read (|
            let~ _ : Ty.tuple [] :=
              M.call_closure (|
                Ty.tuple [],
                M.get_function (| "std::io::stdio::_print", [], [] |),
                [
                  M.read (|
                    let~ args :
                        Ty.tuple
                          [ Ty.apply (Ty.path "&") [] [ Ty.apply (Ty.path "&") [] [ T ] ] ] :=
                      Value.Tuple [ M.borrow (| Pointer.Kind.Ref, t |) ] in
                    let~ args :
                        Ty.apply
                          (Ty.path "array")
                          [ Value.Integer IntegerKind.Usize 1 ]
                          [ Ty.path "core::fmt::rt::Argument" ] :=
                      Value.Array
                        [
                          M.call_closure (|
                            Ty.path "core::fmt::rt::Argument",
                            M.get_associated_function (|
                              Ty.path "core::fmt::rt::Argument",
                              "new_debug",
                              [],
                              [ Ty.apply (Ty.path "&") [] [ T ] ]
                            |),
                            [
                              M.borrow (|
                                Pointer.Kind.Ref,
                                M.deref (|
                                  M.read (| M.SubPointer.get_tuple_field (| args, 0 |) |)
                                |)
                              |)
                            ]
                          |)
                        ] in
                    M.alloc (|
                      Ty.path "core::fmt::Arguments",
                      M.call_closure (|
                        Ty.path "core::fmt::Arguments",
                        M.get_associated_function (|
                          Ty.path "core::fmt::Arguments",
                          "new",
                          [ Value.Integer IntegerKind.Usize 10; Value.Integer IntegerKind.Usize 1 ],
                          []
                        |),
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (|
                              M.mk_byte_str_ref 10 [ 4; 116; 58; 32; 96; 192; 2; 96; 10; 0 ]
                            |)
                          |);
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.borrow (| Pointer.Kind.Ref, args |) |)
                          |)
                        ]
                      |)
                    |)
                  |)
                ]
              |) in
            M.alloc (| Ty.tuple [], Value.Tuple [] |)
          |) in
        let~ _ : Ty.tuple [] :=
          M.read (|
            let~ _ : Ty.tuple [] :=
              M.call_closure (|
                Ty.tuple [],
                M.get_function (| "std::io::stdio::_print", [], [] |),
                [
                  M.read (|
                    let~ args :
                        Ty.tuple
                          [ Ty.apply (Ty.path "&") [] [ Ty.apply (Ty.path "&") [] [ U ] ] ] :=
                      Value.Tuple [ M.borrow (| Pointer.Kind.Ref, u |) ] in
                    let~ args :
                        Ty.apply
                          (Ty.path "array")
                          [ Value.Integer IntegerKind.Usize 1 ]
                          [ Ty.path "core::fmt::rt::Argument" ] :=
                      Value.Array
                        [
                          M.call_closure (|
                            Ty.path "core::fmt::rt::Argument",
                            M.get_associated_function (|
                              Ty.path "core::fmt::rt::Argument",
                              "new_debug",
                              [],
                              [ Ty.apply (Ty.path "&") [] [ U ] ]
                            |),
                            [
                              M.borrow (|
                                Pointer.Kind.Ref,
                                M.deref (|
                                  M.read (| M.SubPointer.get_tuple_field (| args, 0 |) |)
                                |)
                              |)
                            ]
                          |)
                        ] in
                    M.alloc (|
                      Ty.path "core::fmt::Arguments",
                      M.call_closure (|
                        Ty.path "core::fmt::Arguments",
                        M.get_associated_function (|
                          Ty.path "core::fmt::Arguments",
                          "new",
                          [ Value.Integer IntegerKind.Usize 10; Value.Integer IntegerKind.Usize 1 ],
                          []
                        |),
                        [
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (|
                              M.mk_byte_str_ref 10 [ 4; 117; 58; 32; 96; 192; 2; 96; 10; 0 ]
                            |)
                          |);
                          M.borrow (|
                            Pointer.Kind.Ref,
                            M.deref (| M.borrow (| Pointer.Kind.Ref, args |) |)
                          |)
                        ]
                      |)
                    |)
                  |)
                ]
              |) in
            M.alloc (| Ty.tuple [], Value.Tuple [] |)
          |) in
        M.alloc (| Ty.tuple [], Value.Tuple [] |)
      |)))
  | _, _, _ => M.impossible "wrong number of arguments"
  end.

Global Instance Instance_IsFunction_compare_types :
  M.IsFunction.C "generics_multiple_bounds::compare_types" compare_types.
Proof.
Admitted.
Global Typeclasses Opaque compare_types.

(*
fn main() {
    let string = "words";
    let array = [1, 2, 3];
    let vec = vec![1, 2, 3];

    compare_prints(&string);
    //compare_prints(&array);
    // TODO ^ Try uncommenting this.

    compare_types(&array, &vec);
}
*)
Definition main (ε : list Value.t) (τ : list Ty.t) (α : list Value.t) : M :=
  match ε, τ, α with
  | [], [], [] =>
    ltac:(M.monadic
      (M.read (|
        let~ string : Ty.apply (Ty.path "&") [] [ Ty.path "str" ] := mk_str (| "words" |) in
        let~ array :
            Ty.apply (Ty.path "array") [ Value.Integer IntegerKind.Usize 3 ] [ Ty.path "i32" ] :=
          Value.Array
            [
              Value.Integer IntegerKind.I32 1;
              Value.Integer IntegerKind.I32 2;
              Value.Integer IntegerKind.I32 3
            ] in
        let~ vec :
            Ty.apply
              (Ty.path "alloc::vec::Vec")
              []
              [ Ty.path "i32"; Ty.path "alloc::alloc::Global" ] :=
          M.call_closure (|
            Ty.apply
              (Ty.path "alloc::vec::Vec")
              []
              [ Ty.path "i32"; Ty.path "alloc::alloc::Global" ],
            M.get_associated_function (|
              Ty.apply (Ty.path "slice") [] [ Ty.path "i32" ],
              "into_vec",
              [],
              [ Ty.path "alloc::alloc::Global" ]
            |),
            [
              M.call_closure (|
                Ty.apply
                  (Ty.path "alloc::boxed::Box")
                  []
                  [ Ty.apply (Ty.path "slice") [] [ Ty.path "i32" ]; Ty.path "alloc::alloc::Global"
                  ],
                M.pointer_coercion
                  M.PointerCoercion.Unsize
                  (Ty.apply
                    (Ty.path "alloc::boxed::Box")
                    []
                    [
                      Ty.apply
                        (Ty.path "array")
                        [ Value.Integer IntegerKind.Usize 3 ]
                        [ Ty.path "i32" ];
                      Ty.path "alloc::alloc::Global"
                    ])
                  (Ty.apply
                    (Ty.path "alloc::boxed::Box")
                    []
                    [
                      Ty.apply (Ty.path "slice") [] [ Ty.path "i32" ];
                      Ty.path "alloc::alloc::Global"
                    ]),
                [
                  M.read (|
                    M.call_closure (|
                      Ty.apply
                        (Ty.path "alloc::boxed::Box")
                        []
                        [
                          Ty.apply
                            (Ty.path "array")
                            [ Value.Integer IntegerKind.Usize 3 ]
                            [ Ty.path "i32" ];
                          Ty.path "alloc::alloc::Global"
                        ],
                      M.get_associated_function (|
                        Ty.apply
                          (Ty.path "alloc::boxed::Box")
                          []
                          [
                            Ty.apply
                              (Ty.path "array")
                              [ Value.Integer IntegerKind.Usize 3 ]
                              [ Ty.path "i32" ];
                            Ty.path "alloc::alloc::Global"
                          ],
                        "new",
                        [],
                        []
                      |),
                      [
                        M.alloc (|
                          Ty.apply
                            (Ty.path "array")
                            [ Value.Integer IntegerKind.Usize 3 ]
                            [ Ty.path "i32" ],
                          Value.Array
                            [
                              Value.Integer IntegerKind.I32 1;
                              Value.Integer IntegerKind.I32 2;
                              Value.Integer IntegerKind.I32 3
                            ]
                        |)
                      ]
                    |)
                  |)
                ]
              |)
            ]
          |) in
        let~ _ : Ty.tuple [] :=
          M.call_closure (|
            Ty.tuple [],
            M.get_function (|
              "generics_multiple_bounds::compare_prints",
              [],
              [ Ty.apply (Ty.path "&") [] [ Ty.path "str" ] ]
            |),
            [ M.borrow (| Pointer.Kind.Ref, M.deref (| M.borrow (| Pointer.Kind.Ref, string |) |) |)
            ]
          |) in
        let~ _ : Ty.tuple [] :=
          M.call_closure (|
            Ty.tuple [],
            M.get_function (|
              "generics_multiple_bounds::compare_types",
              [],
              [
                Ty.apply (Ty.path "array") [ Value.Integer IntegerKind.Usize 3 ] [ Ty.path "i32" ];
                Ty.apply
                  (Ty.path "alloc::vec::Vec")
                  []
                  [ Ty.path "i32"; Ty.path "alloc::alloc::Global" ]
              ]
            |),
            [
              M.borrow (| Pointer.Kind.Ref, M.deref (| M.borrow (| Pointer.Kind.Ref, array |) |) |);
              M.borrow (| Pointer.Kind.Ref, M.deref (| M.borrow (| Pointer.Kind.Ref, vec |) |) |)
            ]
          |) in
        M.alloc (| Ty.tuple [], Value.Tuple [] |)
      |)))
  | _, _, _ => M.impossible "wrong number of arguments"
  end.

Global Instance Instance_IsFunction_main : M.IsFunction.C "generics_multiple_bounds::main" main.
Proof.
Admitted.
Global Typeclasses Opaque main.

Definition function_table : list (string * PolymorphicFunction.t) :=
  [
    ("generics_multiple_bounds::compare_prints", compare_prints);
    ("generics_multiple_bounds::compare_types", compare_types);
    ("generics_multiple_bounds::main", main)
  ].

Definition trait_method_table : list (string * list Ty.t * Ty.t * string * PolymorphicFunction.t) :=
  [].
