(* Generated by coq-of-rust *)
Require Import CoqOfRust.CoqOfRust.

Module  ProvidedAndRequired.
Section ProvidedAndRequired.
  Class Trait (Self : Set) : Type := {
    required : Ty.function [Ty.apply (Ty.path "ref") [Self]] (Ty.path "i32");
  }.
  
End ProvidedAndRequired.
End ProvidedAndRequired.

Module  Impl_provided_method_ProvidedAndRequired_for_i32.
Section Impl_provided_method_ProvidedAndRequired_for_i32.
  Definition Self : Ty.t := Ty.path "i32".
  
  Parameter required :
      (Ty.apply (Ty.path "ref") [Ty.path "i32"]) -> Ty.path "i32".
  
  Definition AssociatedFunction_required : Instance.t := {
    Notations.double_colon := required;
  }.
  
  Definition ℐ : Instance.t := [("required", required); ("provided", provided)].
End Impl_provided_method_ProvidedAndRequired_for_i32.
End Impl_provided_method_ProvidedAndRequired_for_i32.

Module  Impl_provided_method_ProvidedAndRequired_for_u32.
Section Impl_provided_method_ProvidedAndRequired_for_u32.
  Definition Self : Ty.t := Ty.path "u32".
  
  Parameter required :
      (Ty.apply (Ty.path "ref") [Ty.path "u32"]) -> Ty.path "i32".
  
  Definition AssociatedFunction_required : Instance.t := {
    Notations.double_colon := required;
  }.
  
  Parameter provided :
      (Ty.apply (Ty.path "ref") [Ty.path "u32"]) -> Ty.path "i32".
  
  Definition AssociatedFunction_provided : Instance.t := {
    Notations.double_colon := provided;
  }.
  
  Definition ℐ : Instance.t := [("required", required); ("provided", provided)].
End Impl_provided_method_ProvidedAndRequired_for_u32.
End Impl_provided_method_ProvidedAndRequired_for_u32.

(* #[allow(dead_code)] - function was ignored by the compiler *)
Parameter main : Ty.path "unit".
